"use client";
import {ArrowDownRight,ArrowUpRight,CircleDollarSign,FileText,Plus,ReceiptText,Users,WalletCards} from "lucide-react";
import AppShell from "../components/AppShell";
import styles from "./page.module.css";
const invoices=[["INV-1042","Acme Studio","₹50,740","Due soon"],["INV-1041","Northstar Media","₹28,500","Sent"],["INV-1039","Field Notes Co.","₹76,000","Overdue"],["INV-1038","Aster Works","₹18,900","Paid"]];
const line=(d:string,t:string)=><svg viewBox="0 0 180 46" preserveAspectRatio="none"><path d={d} fill="none" stroke="currentColor" strokeWidth="2.4" strokeLinecap="round"/></svg>;
function Metric({icon:Icon,label,value,meta,tone,path}:{icon:typeof WalletCards;label:string;value:string;meta:string;tone:string;path:string}){return <article className={styles.metric}><div className={styles.metricTop}><span className={styles.icon+" "+styles[tone]}><Icon size={15}/></span><span>{label}</span></div><b>{value}</b><small>{meta}</small><div className={styles.mini+" "+styles[tone]}>{line(path,tone)}</div></article>}
export default function Home(){
return <AppShell title="Dashboard" subtitle="Your financial position, invoices and cash flow at a glance." action={<a href="/invoices/new" className={styles.primary}><Plus size={14}/> New invoice</a>}>
<section className={styles.metrics}>
<Metric icon={WalletCards} label="Outstanding" value="₹1,42,800" meta="8.4% vs last month" tone="purple" path="M2 39 C20 34 30 42 47 31 S71 20 88 29 S111 43 126 22 S149 12 178 20"/>
<Metric icon={ReceiptText} label="Paid invoices" value="₹3,84,200" meta="14 payments this month" tone="green" path="M2 40 C20 30 33 36 49 26 S72 32 88 21 S111 27 126 13 S150 20 178 8"/>
<Metric icon={ArrowDownRight} label="Due soon" value="₹76,400" meta="5 invoices · next 7 days" tone="orange" path="M2 38 C21 38 29 26 44 32 S66 17 82 26 S104 18 119 29 S145 13 178 22"/>
<Metric icon={CircleDollarSign} label="Overdue" value="₹28,500" meta="2 invoices need attention" tone="red" path="M2 34 C21 35 30 23 45 30 S68 18 84 28 S106 17 122 29 S149 13 178 18"/>
</section>
<section className={styles.grid}>
<article className={styles.panel+" "+styles.revenue}><header><div><span>Cash flow</span><h2>Receivables</h2></div><div className={styles.segment}><button className={styles.selected}>Monthly</button><button>Weekly</button></div></header><div className={styles.revenueValue}><b>₹5,63,982</b><span><ArrowUpRight size={11}/> 10.6%</span><small>than last month</small></div><div className={styles.chart}><div className={styles.axis}><span>₹60k</span><span>₹40k</span><span>₹20k</span><span>₹0</span></div><svg viewBox="0 0 700 240" preserveAspectRatio="none"><path d="M0 210 C35 174 58 205 84 169 S132 188 158 128 S207 148 230 101 S274 131 304 91 S346 70 370 114 S417 149 444 87 S488 114 518 59 S562 77 594 45 S642 82 700 24" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/></svg></div><div className={styles.months}>{["Apr","May","Jun","Jul","Aug","Sep","Oct"].map(m=><span key={m}>{m}</span>)}</div></article>
<article className={styles.panel+" "+styles.collection}><header><div><span>Performance</span><h2>Collection</h2></div><button className={styles.more}>•••</button></header><div className={styles.collectionBody}><div className={styles.donut}><div><b>68%</b><span>Collected</span></div></div><div className={styles.legend}><div><i className={styles.green}/><span>Paid</span><b>68%</b></div><div><i className={styles.purpleDot}/><span>Pending</span><b>22%</b></div><div><i className={styles.redDot}/><span>Overdue</span><b>10%</b></div></div></div></article>
</section>
<section className={styles.grid+" "+styles.second}>
<article className={styles.panel}><header><div><span>Receivables</span><h2>Recent invoices</h2></div><a href="/invoices">View all <ArrowUpRight size={12}/></a></header><div className={styles.table}><div className={styles.thead}><span>Invoice</span><span>Client</span><span>Amount</span><span>Status</span></div>{invoices.map(([id,client,amount,status])=><a href="/invoices" className={styles.row} key={id}><span className={styles.mono}>{id}</span><span>{client}</span><b>{amount}</b><i className={styles["status_"+status.toLowerCase().replace(" ","_")]}>{status}</i></a>)}</div></article>
<article className={styles.panel}><header><div><span>Quick actions</span><h2>Needs attention</h2></div><span className={styles.badge}>3</span></header><div className={styles.actions}><a href="/invoices"><span className={styles.actionIcon+" "+styles.red}>2</span><div><b>Overdue invoices</b><small>Follow up on past-due payments</small></div><ArrowUpRight size={13}/></a><a href="#"><span className={styles.actionIcon+" "+styles.orange}>2</span><div><b>Quotes awaiting approval</b><small>Client action is still pending</small></div><ArrowUpRight size={13}/></a><a href="#"><span className={styles.actionIcon+" "+styles.greenText}>1</span><div><b>Payment received</b><small>A new payment arrived today</small></div><ArrowUpRight size={13}/></a></div></article>
</section>
<section className={styles.bottomGrid}><article className={styles.panel+" "+styles.spending}><header><div><span>Breakdown</span><h2>Spending</h2></div><span>October</span></header><div className={styles.spendRows}><div><i className={styles.purpleBar}/><span>Investment</span><b>₹1,415</b><small>/ ₹2,000</small></div><div><i className={styles.cyanBar}/><span>Installment</span><b>₹1,567</b><small>/ ₹5,000</small></div><div><i className={styles.orangeBar}/><span>Restaurant</span><b>₹487</b><small>/ ₹1,000</small></div><div><i className={styles.blueBar}/><span>Property</span><b>₹3,890</b><small>/ ₹4,000</small></div></div></article><article className={styles.panel+" "+styles.quick}><header><div><span>Actions</span><h2>Quick transfer</h2></div></header><div className={styles.transfer}><div><span className={styles.transferAvatar}>S</span><div><b>Samsul</b><small>Vendor · ••24</small></div></div><button>Transfer</button></div><div className={styles.transferAmount}><small>Amount</small><b>₹ 0</b></div></article></section>
</AppShell>}
